---
- hosts: 127.0.0.1 
  connection: local

  tasks:
  - name: ripgrep
    become: true
    apt:
      deb: https://github.com/BurntSushi/ripgrep/releases/download/14.1.0/ripgrep_14.1.0-1_amd64.deb
      state: present
